database:
  url: "mysql+pymysql://${HTMLDATAEXTRACTOR_DB_USER}:${HTMLDATAEXTRACTOR_DB_PASSWORD_URLENCODED}@192.168.36.36:3306/wangfanqi_test?charset=utf8mb4"

source:
  table: "temp_商业补充保险_20250523"
  id_column: ""
  info_id_column: "SourceURL"
  title_column: "Title"
  html_column: ""
  text_column: "Content"
  article_time_column: "AuditTime"
  audit_time_column: "AuditTime"
  region_column: "areaname"
  related_info_column: "Source"

query:
  where: ""
  limit: 1000
  order_by: "AuditTime ASC"

direct_field_columns:
  文章时间: ""
  审核日期: ""
  info_id: ""
  地区名称: ""
  个人账户计入办法: ""
  个人账户使用范围: ""
  病种名称: ""
  类型: ""
  标化类型: ""
  保险类型: "insurancetypename"
  人员类型: ""
  病种类型: ""
  就诊地域: ""
  医院类型: ""
  就诊情况: ""
  区间: ""
  起付标准: ""
  补助限额: ""
  报销比例: ""
  备注: ""
  相关资讯: ""
  审核状态0待审核1已审核: ""
  执行状态: ""
  开始执行时间: ""
  结束时间: ""
  是否需要手动修改执行状态(1是0否): ""
